---
title: "Figures for Plots"
output: html_notebook
---

```{r}
#Preparing the data and the function
library(ggplot2)
library(scales)
library(tidyr)
```

# Percentage differences between WT and IL-KO
```{r, echo = FALSE}
library(scales)
ActivData = read.csv('~/my.work/PhD/HomestaticExpansionProject/ModelData/TCellActivationSummary_EdittedinR.csv')

ActivData$pct_CD4_CD44_pos_CD62L_neg = ActivData$pct_CD4_CD44_pos_CD62L_neg/100
ggplot(ActivData, aes(Age, pct_CD4_CD44_pos_CD62L_neg, shape = Genotype)) + 
  geom_point(position = position_dodge(1), size = 4)+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_y_continuous(breaks = seq(0,max(ActivData$pct_CD4_CD44_pos_CD62L_neg, na.rm = TRUE),
                                  length.out =5),
                     labels = label_percent())+
  labs(titles = "Activated T Cell Percentage", x = "Age in Days", y = "CD44+CD62- Percentage")+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
        legend.key = element_rect(fill = "white", colour = "black"),
        legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text(colour="black", size=20),
        axis.title.y = element_text(colour = "black", size = 20),
        plot.title = element_text(lineheight=.8, size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  stat_summary(aes(group=Genotype, color = Genotype), fun=mean, geom="line")


CD69Data = read.csv('~/my.work/PhD/HomestaticExpansionProject/ModelData/CD69DataFromGen.csv')
#Removing day 0, because it is always weird
CD69Data = subset(CD69Data, Age > 0)
CD69Data$CD4CD69_pct = CD69Data$CD4CD69_pct / 100
ggplot(CD69Data, aes(Age, CD4CD69_pct, shape = Genotype)) + 
  geom_point(position = position_dodge(1), size = 4)+
  scale_x_continuous(breaks = seq(4,20,2))+
  scale_y_continuous(breaks = seq(0,max(CD69Data$CD4CD69_pct, na.rm = TRUE),
                                  length.out =5),
                     labels = label_percent())+
  labs(titles = "Activating T Cell Percentage", x = "Age in Days", y = "CD4+CD69+ Percentage")+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text(colour="black", size=20),
        axis.title.y = element_text(colour = "black", size = 20),
        plot.title = element_text(lineheight=.8, size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  stat_summary(aes(group=Genotype, color = Genotype), fun=mean, geom="line")


TregDF = read.csv('~/my.work/PhD/HomestaticExpansionProject/ModelData/AfterCalculations.csv')
#Removing day 0, because it is always weird
TregDF = subset(TregDF, Age > 0 & Age < 50)

ggplot(TregDF, aes(Age, X4TregRatio, shape = Genotype)) + 
  geom_point(position = position_dodge(1), size = 4)+
  scale_x_continuous(breaks = seq(4,20,2))+
  scale_y_continuous(breaks = seq(0,max(TregDF$X4TregRatio, na.rm = TRUE),
                                  length.out =5),
                     labels = label_percent())+
  labs(titles = "Regulatory T Cell Percentage", x = "Age in Days", y = "CD4+Foxp3+ Percentage")+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text(colour="black", size=20),
        axis.title.y = element_text(colour = "black", size = 20),
        plot.title = element_text(lineheight=.8, size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  stat_summary(aes(group=Genotype, color = Genotype), fun=mean, geom="line")
```
#Colorblind safe choices
```{r}
# Color changes
#3EECF0 --> #3EECF0
#3027E6 --> #3027E6
#FAEF41 --> #FAEF41
#DB3D2F --> #DB3D2F
```

```{r}
library(tidyr)
library(ggplot2)
```

#Activation Data
```{r}
WTProl = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/WTProl.csv')
KOProl = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/KOProl.csv')
ActivatedWTSpleen = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/ActivatedWTSpleen.csv')
ActivatedKOSpleen = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/ActivatedKOSpleen.csv')

#######################################
#           Wild Type
#######################################

#Setting up the data
ActivatedTWT = subset(ActivatedWTSpleen, select = c("ActivatedCD4CT", "ActivatedNaiveCT", "Age" ))
LongActivatedTWT = gather(ActivatedTWT, variable, value, -Age)
ActivatedTProlWT = subset(WTProl, select = c("ActivatedProlCT", "Age"))
LongActivatedTProlWT = gather(ActivatedTProlWT, variable, value, -Age)
LongActivatedTWT = rbind(LongActivatedTWT, LongActivatedTProlWT)

#Changing the Names and order
LongActivatedTWT$variable = factor(LongActivatedTWT$variable, levels = c("ActivatedCD4CT", "ActivatedNaiveCT", "ActivatedProlCT"), 
                              labels = c("Total Activated CD4","Naive Derived", "Proliferating"))

#Creating Y axis label
Ylabel = expression(Cell ~ Counts ~ (10^6))

ggplot(LongActivatedTWT, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "WT Activated Populations", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 7072000), breaks = c(0, 1768000, 3536000, 5304000, 7072000), labels = c(0, 1.7, 3.5, 5.3, 7.0))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))

#######################################
#           IL-2 KO
#######################################

#Setting up the data
ActivatedTKO = subset(ActivatedKOSpleen, select = c("ActivatedCD4CT", "ActivatedNaiveCT", "Age" ))
LongActivatedTKO = gather(ActivatedTKO, variable, value, -Age)
ActivatedTProlKO = subset(KOProl, select = c("ActivatedProlCT", "Age"))
LongActivatedTProlKO = gather(ActivatedTProlKO, variable, value, -Age)
LongActivatedTKO = rbind(LongActivatedTKO, LongActivatedTProlKO)

#Changing the Names and order
LongActivatedTKO$variable = factor(LongActivatedTKO$variable, levels = c("ActivatedCD4CT", "ActivatedNaiveCT", "ActivatedProlCT"), 
                              labels = c("Total Activated CD4","Naive Derived", "Proliferating"))

ggplot(LongActivatedTKO, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "KO Activated Populations", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 7072000), breaks = c(0, 1768000, 3536000, 5304000, 7072000), labels = c(0, 1.7, 3.5, 5.3, 7.0))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))


#######################################
#           Naive Derived Activated T Cells
#######################################
ActivatedWTSpleen$ActivatedNaiveCTWT = ActivatedWTSpleen$ActivatedNaiveCT
#Setting up Data
ActivatedNaiveWT = subset(ActivatedWTSpleen, select = c("ActivatedNaiveCTWT", "Age"))
LongActivatedNaiveWT = gather(ActivatedNaiveWT, variable, value, -Age)

ActivatedNaiveKO = subset(ActivatedKOSpleen, select = c("ActivatedNaiveCT", "Age"))
LongActivatedNaiveKO = gather(ActivatedNaiveKO, variable, value, -Age)
LongActivatedNaive = rbind(LongActivatedNaiveWT, LongActivatedNaiveKO)

LongActivatedNaive$variable = factor(LongActivatedNaive$variable, levels = c("ActivatedNaiveCTWT", "ActivatedNaiveCT"), labels = c("WT", "KO"))

#Creating Y axis label
Ylabel = expression(Cell ~ Counts)

ggplot(LongActivatedNaive, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "Naive Derived Activated T Cells", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        #axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  # scale_y_continuous(breaks = seq(0,3880000, length.out = 5))+
  scale_y_continuous(limits=c(0, 7072000), breaks = c(0, 1768000, 3536000, 5304000, 7072000), labels = c(0, 1.7, 3.5, 5.3, 7.0))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))


#####################################################
#         Proliferating Activated T Cells
#####################################################
WTProl$ActivatedProlCTWT = WTProl$ActivatedProlCT

#Setting up Data
ActivatedProlCTWT = subset(WTProl, select = c("ActivatedProlCTWT", "Age"))
LongActivatedProlCTWT = gather(ActivatedProlCTWT, variable, value, -Age)

ActivatedProlCTKO = subset(KOProl, select = c("ActivatedProlCT", "Age"))
LongActivatedProlCTKO = gather(ActivatedProlCTKO, variable, value, -Age)
LongActivatedProlCT = rbind(LongActivatedProlCTWT, LongActivatedProlCTKO)

LongActivatedProlCT$variable = factor(LongActivatedProlCT$variable, levels = c("ActivatedProlCTWT", "ActivatedProlCT"), labels = c("WT", "KO"))

#Creating Y axis label
Ylabel = expression(Cell ~ Counts)

ggplot(LongActivatedProlCT, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "Proliferating Activated T Cells", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        #axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  # scale_y_continuous(breaks =seq(0,2138000, length.out = 5 ))+
  scale_y_continuous(limits=c(0, 7072000), breaks = c(0, 1768000, 3536000, 5304000, 7072000), labels = c(0, 1.7, 3.5, 5.3, 7.0))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))

```
#Naive T Cells
```{r}

WTProl = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/WTProl.csv')
KOProl = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/KOProl.csv')
ActivatedWTSpleen = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/ActivatedWTSpleen.csv')
ActivatedKOSpleen = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/ActivatedKOSpleen.csv')


#######################################
#           Wild Type
#######################################

#Setting up the data
NaiveWT = subset(ActivatedWTSpleen, select = c("NaiveCT", "ThymicNaive", "Age" ))
LongNaiveWT = gather(NaiveWT, variable, value, -Age)
NaiveProlWT = subset(WTProl, select = c("NaiveProlCT", "Age"))
LongNaiveProlWT = gather(NaiveProlWT, variable, value, -Age)
LongNaiveWT = rbind(LongNaiveWT, LongNaiveProlWT)

#Changing the Names and order
LongNaiveWT$variable = factor(LongNaiveWT$variable, levels = c("NaiveCT", "ThymicNaive", "NaiveProlCT"), 
                              labels = c("Total Naive","Thymic Derived", "Proliferating"))
#Creating Y axis label
Ylabel = expression(Cell ~ Counts ~ (10^6))

ggplot(LongNaiveWT, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "WT Naive Populations", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 4835000), breaks = c(0, 1208750, 2417500, 3626250, 4835000), labels = c(0, 1.2, 2.4, 3.6, 4.8))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))

#######################################
#           IL-2 KO
#######################################

#Setting up the data
NaiveKO = subset(ActivatedKOSpleen, select = c("NaiveCT", "ThymicNaive", "Age" ))
LongNaiveKO = gather(NaiveKO, variable, value, -Age)
NaiveProlKO = subset(KOProl, select = c("NaiveProlCT", "Age"))
LongNaiveProlKO = gather(NaiveProlKO, variable, value, -Age)
LongNaiveKO = rbind(LongNaiveKO, LongNaiveProlKO)

#Changing the Names and order
LongNaiveKO$variable = factor(LongNaiveKO$variable, levels = c("NaiveCT", "ThymicNaive", "NaiveProlCT"), 
                              labels = c("Total Naive","Thymic Derived", "Proliferating"))

ggplot(LongNaiveKO, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "KO Naive Populations", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 4835000), breaks = c(0, 1208750, 2417500, 3626250, 4835000), labels = c(0, 1.2, 2.4, 3.6, 4.8))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))
```
#Regulatory T Cells
```{r}

WTProl = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/WTProl.csv')
KOProl = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/KOProl.csv')
ActivatedWTSpleen = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/ActivatedWTSpleen.csv')
ActivatedKOSpleen = read.csv('~/my.work/PhD/HomestaticExpansionProject/Code/Modeling/Matlab/RawData/ActivatedKOSpleen.csv')

#######################################
#           Wild Type
#######################################

#Setting up Data
TregsWT = subset(ActivatedWTSpleen, select = c("X4TregCT", "NaiveDerivedTregsCT", "ThymicDerivedTregsCT", "Age" ))
LongTregsWT = gather(TregsWT, variable, value, -Age)
TregsProlWT = subset(WTProl, select = c("X4TregProlCT", "Age"))
LongTregsProlWT = gather(TregsProlWT, variable, value, -Age)
LongTregsWT = rbind(LongTregsWT, LongTregsProlWT)

#Changing Names and Order
LongTregsWT$variable = factor(LongTregsWT$variable, levels = c("X4TregCT", "X4TregProlCT", "NaiveDerivedTregsCT", "ThymicDerivedTregsCT"), 
                              labels = c("Total Tregs","Proliferating", "Peripherally Derived", "Thymic Derived"))
#Creating Y axis label
Ylabel = expression(Cell ~ Counts ~ (10^5))

ggplot(LongTregsWT, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "WT Treg Populations", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        #axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 1030000), breaks = c(0, 250000, 500000, 750000, 1030000), labels = c(0, 2.5, 5, 7.5, 10.3))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))


#######################################
#           IL-2 KO
#######################################

#Setting up Data
TregsKO = subset(ActivatedKOSpleen, select = c("X4TregCT", "NaiveDerivedTregsCT", "ThymicDerivedTregsCT", "Age" ))
LongTregsKO = gather(TregsKO, variable, value, -Age)
TregsProlKO = subset(KOProl, select = c("X4TregProlCT", "Age"))
LongTregsProlKO = gather(TregsProlKO, variable, value, -Age)
LongTregsKO = rbind(LongTregsKO, LongTregsProlKO)

#Changing Names and Order
LongTregsKO$variable = factor(LongTregsKO$variable, levels = c("X4TregCT", "X4TregProlCT", "NaiveDerivedTregsCT", "ThymicDerivedTregsCT"), 
                              labels = c("Total Tregs","Proliferating", "Peripherally Derived", "Thymic Derived"))

ggplot(LongTregsKO, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "KO Treg Populations", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 1030000), breaks = c(0, 250000, 500000, 750000, 1030000), labels = c(0, 2.5, 5, 7.5, 10.3))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))


##################################################
#           Proliferating Tregs
##################################################
WTProl$TregProlWT = WTProl$X4TregProlCT
#Setting up Data
ProlTregsWT = subset(WTProl, select = c("TregProlWT", "Age"))
LongProlTregsWT = gather(ProlTregsWT, variable, value, -Age)
ProlTregsKO = subset(KOProl, select = c("X4TregProlCT", "Age"))
LongProlTregsKO = gather(ProlTregsKO, variable, value, -Age)
LongProlTregs = rbind(LongProlTregsWT, LongProlTregsKO)

LongProlTregs$variable = factor(LongProlTregs$variable, levels = c("TregProlWT", "X4TregProlCT"), labels = c("WT Tregs", "KO Tregs"))

#Changing Names and Order
LongTregsWT$variable = factor(LongTregsWT$variable, levels = c("X4TregCT", "X4TregProlCT", "NaiveDerivedTregsCT", "ThymicDerivedTregsCT"), 
                              labels = c("Total Tregs","Proliferating", "Peripherally Derived", "Thymic Derived"))
#Creating Y axis label
Ylabel = expression(Cell ~ Counts ~ (10^5))

ggplot(LongProlTregs, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "Proliferating Treg", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        #axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 1030000), breaks = c(0, 250000, 500000, 750000, 1030000), labels = c(0, 2.5, 5, 7.5, 10.3))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))


#######################################
#           Naive Derived Tregs
#######################################
ActivatedWTSpleen$NaiveDerivedTregsCTWT = ActivatedWTSpleen$NaiveDerivedTregsCT
#Setting up Data
NaiveTregsWT = subset(ActivatedWTSpleen, select = c("NaiveDerivedTregsCTWT", "Age"))
LongNaiveTregsWT = gather(NaiveTregsWT, variable, value, -Age)

NaiveTregsKO = subset(ActivatedKOSpleen, select = c("NaiveDerivedTregsCT", "Age"))
LongNaiveTregsKO = gather(NaiveTregsKO, variable, value, -Age)
LongProlTregs = rbind(LongNaiveTregsWT, LongNaiveTregsKO)

LongProlTregs$variable = factor(LongProlTregs$variable, levels = c("NaiveDerivedTregsCTWT", "NaiveDerivedTregsCT"), labels = c("WT", "KO"))

#Changing Names and Order
LongTregsWT$variable = factor(LongTregsWT$variable, levels = c("X4TregCT", "X4TregProlCT", "NaiveDerivedTregsCT", "ThymicDerivedTregsCT"), 
                              labels = c("Total Tregs","Proliferating", "Peripherally Derived", "Thymic Derived"))
#Creating Y axis label
Ylabel = expression(Cell ~ Counts )

ggplot(LongProlTregs, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "Peripherally Derived Tregs", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text( colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        #axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 1030000), breaks = c(0, 250000, 500000, 750000, 1030000), labels = c(0, 2.5, 5, 7.5, 10.3))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))


#######################################
#           Thymic Tregs
#######################################

ActivatedWTSpleen$ThymicDerivedTregsCTWT = ActivatedWTSpleen$ThymicDerivedTregsCT
#Setting up Data
ThymicTregsWT = subset(ActivatedWTSpleen, select = c("ThymicDerivedTregsCTWT", "Age"))
LongThymicTregsWT = gather(ThymicTregsWT, variable, value, -Age)

ThymicTregsKO = subset(ActivatedKOSpleen, select = c("ThymicDerivedTregsCT", "Age"))
LongThymicTregsKO = gather(ThymicTregsKO, variable, value, -Age)
LongThymicTregs = rbind(LongThymicTregsWT, LongThymicTregsKO)

LongThymicTregs$variable = factor(LongThymicTregs$variable, levels = c("ThymicDerivedTregsCTWT", "ThymicDerivedTregsCT"), labels = c("WT", "KO"))

#Creating Y axis label
Ylabel = expression(Cell ~ Counts)

ggplot(LongThymicTregs, aes(x = Age, y = value, color = variable)) + 
  geom_point(position = position_dodge(1), size = 2)+
  stat_summary(aes(group=variable, color = variable), fun=mean, geom="line")+
  labs(titles = "Thymic Derived Tregs", x = "Age in Days", y = Ylabel)+
  theme(panel.background = element_rect(fill = "white", colour = "black", size = 2),
                 legend.key = element_rect(fill = "white", colour = "black"),
                 legend.background = (element_rect(colour= "black", fill = "white")),
        axis.title.x = element_text(colour="black", size=20),
        axis.title.y = element_text( colour = "black", size = 20),
        plot.title = element_text(lineheight=.8,  size = 20),
        #axis.ticks.length=unit(.25, "cm"),
        text = element_text(size=20))+
  scale_y_continuous(limits=c(0, 1030000), breaks = c(0, 250000, 500000, 750000, 1030000), labels = c(0, 2.5, 5, 7.5, 10.3))+
  scale_x_continuous(breaks = c(0,5,10,15,18))+
  scale_color_manual(values = c("#3EECF0", "#3027E6", "#DB3D2F", "#FAEF41"))+
  guides(color = guide_legend("Legend"))
```










